import Database from "better-sqlite3";
import path from "path";
import fs from "fs";

const DB_PATH = path.join(__dirname, "..", "data", "immobiliare.db");

fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });

if (fs.existsSync(DB_PATH)) {
  fs.unlinkSync(DB_PATH);
}

const db = new Database(DB_PATH);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

db.exec(`
  CREATE TABLE IF NOT EXISTS zones (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    province TEXT NOT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL,
    price REAL,
    rent_lt REAL,
    yield_lt REAL,
    yield_st REAL,
    score_10y REAL,
    trend TEXT DEFAULT 'stable',
    apprec REAL,
    inv_min INTEGER,
    inv_max INTEGER,
    flip_score REAL,
    energy_premium REAL,
    typical_discount REAL,
    dom INTEGER,
    fg_stock REAL,
    flip_note TEXT,
    note TEXT,
    tags TEXT DEFAULT '[]',
    drivers TEXT DEFAULT '[]',
    risks TEXT DEFAULT '[]',
    updated_at TEXT DEFAULT (datetime('now')),
    created_at TEXT DEFAULT (datetime('now'))
  );

  CREATE TABLE IF NOT EXISTS price_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id TEXT NOT NULL REFERENCES zones(id),
    price REAL NOT NULL,
    source TEXT,
    recorded_at TEXT DEFAULT (datetime('now'))
  );

  CREATE TABLE IF NOT EXISTS scrape_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    status TEXT NOT NULL,
    zones_updated INTEGER DEFAULT 0,
    error TEXT,
    run_at TEXT DEFAULT (datetime('now'))
  );
`);

const ZONES = [
  { id: 'sandona', name: 'San Donà di Piave', province: 'VE', x: 690, y: 360, price: 2012, rentLT: 8.5, yieldLT: 6.0, yieldST: null, score10y: 6.5, trend: 'up', apprec: 4.5, invMin: 80, invMax: 130, flipScore: 4.5, energyPremium: 8, typicalDiscount: 18, dom: 90, fgStock: 58, flipNote: 'Premio energetico debole, DOM lungo. Solo buy-to-rent.', drivers: ['Sanitario ULSS 4', 'Hub residenziale'], risks: ['Indice vecchiaia ULSS 4 >250'], note: '+19% prezzi YoY 2025. Capofila Veneto Orientale.', tags: ['Long-term'] },
  { id: 'noventa', name: 'Noventa di Piave', province: 'VE', x: 670, y: 365, price: 1658, rentLT: 8.8, yieldLT: 6.5, yieldST: null, score10y: 7.0, trend: 'up', apprec: 3.5, invMin: 35, invMax: 60, flipScore: 3.5, energyPremium: 6, typicalDiscount: 15, dom: 100, fgStock: 55, flipNote: 'Mercato thin, NO flip. Solo buy-to-rent.', drivers: ['Outlet 3,6M visitatori', 'Logistica A4', 'Posto movimento ferroviario 2026'], risks: ['Comune piccolo'], note: 'Designer Outlet + futura velocizzazione ferroviaria.', tags: ['Long-term', 'Emerging'] },
  { id: 'musile', name: 'Musile di Piave', province: 'VE', x: 695, y: 380, price: 1400, rentLT: 9.2, yieldLT: 7.8, yieldST: null, score10y: 6.5, trend: 'up', apprec: 3.0, invMin: 25, invMax: 45, flipScore: 3.0, energyPremium: 6, typicalDiscount: 15, dom: 110, fgStock: 60, flipNote: 'Mercato thin, NO flip.', drivers: ['Cintura San Donà-Jesolo', 'Crescita +32,5%'], risks: ['Servizi limitati'], note: 'A 10km da Jesolo, demograficamente in crescita.', tags: ['Mispriced', 'Long-term'] },
  { id: 'meolo', name: 'Meolo', province: 'VE', x: 660, y: 390, price: 900, rentLT: 7.5, yieldLT: 8.0, yieldST: null, score10y: 4.0, trend: 'down', apprec: -0.5, invMin: 15, invMax: 28, flipScore: 2.0, energyPremium: 4, typicalDiscount: 20, dom: 150, fgStock: 65, flipNote: 'Demografia debole, NO flip.', drivers: ['Bassi prezzi'], risks: ['Demografia debole', 'Periferia rurale'], note: 'Yield alto ma rischio strutturale demografico.', tags: ['Rischio demografico'] },
  { id: 'quartoaltino', name: "Quarto d'Altino", province: 'VE', x: 635, y: 405, price: 1384, rentLT: 9.0, yieldLT: 7.0, yieldST: null, score10y: 6.5, trend: 'up', apprec: 3.0, invMin: 20, invMax: 40, flipScore: 4.0, energyPremium: 8, typicalDiscount: 18, dom: 80, fgStock: 55, flipNote: 'TAV beneficiario ma mercato piccolo.', drivers: ['SFMR Venezia', 'H-Farm vicinanza', 'TAV Fase 1 giugno 2026'], risks: [], note: 'Beneficiario TAV Mestre-Trieste.', tags: ['Long-term', 'Emerging'] },
  { id: 'marcon', name: 'Marcon', province: 'VE', x: 615, y: 415, price: 1760, rentLT: 10.0, yieldLT: 6.3, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 30, invMax: 55, flipScore: 4.5, energyPremium: 8, typicalDiscount: 15, dom: 75, fgStock: 50, flipNote: 'Hinterland VE, flip marginale.', drivers: ['Hinterland Venezia/Mestre'], risks: [], note: 'Cintura veneziana, stabile.', tags: ['Long-term'] },
  { id: 'jesolo', name: 'Jesolo (Lido)', province: 'VE', x: 705, y: 410, price: 4500, rentLT: 26.0, yieldLT: 6.8, yieldST: 7.5, score10y: 7.0, trend: 'stable', apprec: 4.0, invMin: 280, invMax: 450, flipScore: 5.5, energyPremium: 10, typicalDiscount: 12, dom: 90, fgStock: 65, flipNote: 'Premium balneare, flip su appartamenti vista mare.', drivers: ['5,5M presenze 2024', 'Premium balneare'], risks: ['Reg. UE 1028/2024', 'LdB 2026 soglia 3 immobili'], note: '1° per arrivi in Veneto. Mercato STR maturo.', tags: ['Short-term', 'Premium'] },
  { id: 'jesolopaese', name: 'Jesolo Paese', province: 'VE', x: 695, y: 400, price: 2000, rentLT: 9.9, yieldLT: 6.0, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 50, invMax: 90, flipScore: 4.0, energyPremium: 7, typicalDiscount: 15, dom: 85, fgStock: 58, flipNote: 'Lato continentale, flip locale modesto.', drivers: ['Lato continentale Jesolo'], risks: [], note: 'Mispricing vs Lido.', tags: ['Mispriced'] },
  { id: 'caorle', name: 'Caorle', province: 'VE', x: 770, y: 405, price: 3490, rentLT: 23.5, yieldLT: 6.0, yieldST: 8.5, score10y: 6.0, trend: 'stable', apprec: 3.0, invMin: 220, invMax: 380, flipScore: 5.0, energyPremium: 9, typicalDiscount: 12, dom: 95, fgStock: 62, flipNote: 'Turismo tedesco, flip per STR-ready.', drivers: ['Turismo qualità tedesca', '4,5M presenze'], risks: ['CIN/SCIA stretta'], note: 'Revenue €24K/anno Airbnb medio.', tags: ['Short-term'] },
  { id: 'bibione', name: 'Bibione', province: 'VE', x: 830, y: 405, price: 3170, rentLT: 10.2, yieldLT: 4.0, yieldST: 7.0, score10y: 4.5, trend: 'down', apprec: 0.5, invMin: 380, invMax: 600, flipScore: 2.5, energyPremium: 5, typicalDiscount: 8, dom: 180, fgStock: 70, flipNote: 'Saturazione, NO flip.', drivers: ['5,57M presenze (>Jesolo)'], risks: ['Early Saturation', 'Revenue -8,5% YoY', 'Reg. UE 1028'], note: '4,3M presenze in alloggi privati: rischio massimo.', tags: ['Saturazione', 'Da disinvestire'] },
  { id: 'cavallino', name: 'Cavallino-Treporti', province: 'VE', x: 685, y: 435, price: 2858, rentLT: 14.5, yieldLT: 5.8, yieldST: 9.5, score10y: 7.0, trend: 'stable', apprec: 4.0, invMin: 110, invMax: 200, flipScore: 5.0, energyPremium: 10, typicalDiscount: 10, dom: 80, fgStock: 55, flipNote: 'Open-air dominante, flip su appartamenti residenziali.', drivers: ['6,76M presenze (>Rimini)', 'Open-air dominante'], risks: ['Saturazione tetto'], note: '5ª destinazione italiana dopo Roma/Milano/Firenze/Venezia.', tags: ['Short-term', 'Mispriced'] },
  { id: 'eraclea', name: 'Eraclea Mare', province: 'VE', x: 735, y: 405, price: 1750, rentLT: 9.3, yieldLT: 6.8, yieldST: 9.5, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 60, invMax: 110, flipScore: 4.0, energyPremium: 7, typicalDiscount: 15, dom: 100, fgStock: 60, flipNote: 'Mercato piccolo, flip su STR-ready.', drivers: ['First-mover STR', 'Qualità tedesca'], risks: ['Mercato piccolo'], note: 'Sottovalutata, cluster minore.', tags: ['Mispriced', 'Short-term'] },
  { id: 'venezia', name: 'Venezia centro', province: 'VE', x: 640, y: 445, price: 5884, rentLT: 19.0, yieldLT: 4.0, yieldST: 14.2, score10y: 6.0, trend: 'down', apprec: 1.5, invMin: 450, invMax: 800, flipScore: 4.5, energyPremium: 12, typicalDiscount: 8, dom: 120, fgStock: 75, flipNote: 'Vincoli paesaggistici alti, CAPEX altissimo.', drivers: ['13,3M pernottamenti 2024'], risks: ['Moratoria STR 31/12/2026', 'Reg. 120gg', '52% case turistiche'], note: 'Asset rifugio CIN attivo. Closed market.', tags: ['Premium', 'Regolamentazione'] },
  { id: 'mestre', name: 'Mestre/Marghera', province: 'VE', x: 615, y: 440, price: 1906, rentLT: 12.9, yieldLT: 7.5, yieldST: 10.0, score10y: 7.5, trend: 'up', apprec: 4.5, invMin: 250, invMax: 420, flipScore: 6.0, energyPremium: 9, typicalDiscount: 20, dom: 60, fgStock: 65, flipNote: 'Stock F/G alto, deal-flow buono, premio energetico modesto.', drivers: ['Proxy Venezia no moratoria', 'VEGA Parco Scientifico', 'M9 Mestre'], risks: ['Possibile estensione moratoria'], note: 'Alternativa sostenibile Venezia 10min treno.', tags: ['Mispriced', 'Long-term'] },
  { id: 'portogruaro', name: 'Portogruaro', province: 'VE', x: 800, y: 365, price: 1500, rentLT: 8.5, yieldLT: 6.5, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 70, invMax: 120, flipScore: 3.5, energyPremium: 6, typicalDiscount: 18, dom: 100, fgStock: 58, flipNote: 'Mercato locale, flip marginale.', drivers: ['Università', 'Sanità'], risks: [], note: 'Mercato stabile, baricentro Veneto Orientale.', tags: ['Long-term'] },
  { id: 'chioggia', name: 'Chioggia/Sottomarina', province: 'VE', x: 590, y: 510, price: 2528, rentLT: 11.4, yieldLT: 5.4, yieldST: 13.5, score10y: 5.5, trend: 'stable', apprec: 2.0, invMin: 180, invMax: 300, flipScore: 4.5, energyPremium: 8, typicalDiscount: 15, dom: 95, fgStock: 60, flipNote: 'STR estivo, flip su seconde case.', drivers: ['Sottomarina balneare'], risks: ['Stagionalità forte'], note: 'STR estivo concentrato.', tags: ['Stagionale'] },
  { id: 'mira', name: 'Mira', province: 'VE', x: 580, y: 460, price: 1736, rentLT: 10.6, yieldLT: 7.3, yieldST: null, score10y: 6.5, trend: 'stable', apprec: 2.5, invMin: 50, invMax: 95, flipScore: 4.5, energyPremium: 8, typicalDiscount: 18, dom: 80, fgStock: 55, flipNote: 'Riviera Brenta, flip locale.', drivers: ['Riviera Brenta', 'Treno VE/PD'], risks: [], note: 'Connettività doppia capitale.', tags: ['Long-term', 'Mispriced'] },
  { id: 'mirano', name: 'Mirano', province: 'VE', x: 585, y: 440, price: 2227, rentLT: 10.0, yieldLT: 5.4, yieldST: null, score10y: 6.5, trend: 'stable', apprec: 4.0, invMin: 60, invMax: 110, flipScore: 5.0, energyPremium: 9, typicalDiscount: 15, dom: 75, fgStock: 50, flipNote: 'Cintura veneziana, flip qualità.', drivers: ['Cintura veneziana qualità'], risks: [], note: '+14% YoY 2026.', tags: ['Long-term'] },
  { id: 'dolo', name: 'Dolo', province: 'VE', x: 565, y: 470, price: 1700, rentLT: 9.5, yieldLT: 6.7, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 40, invMax: 75, flipScore: 4.0, energyPremium: 7, typicalDiscount: 18, dom: 85, fgStock: 55, flipNote: 'Riviera Brenta interna, flip modesto.', drivers: ['Riviera Brenta interna'], risks: [], note: 'Mercato locale stabile.', tags: ['Long-term'] },
  { id: 'treviso', name: 'Treviso città', province: 'TV', x: 560, y: 370, price: 2320, rentLT: 11.3, yieldLT: 5.8, yieldST: null, score10y: 8.5, trend: 'up', apprec: 4.0, invMin: 320, invMax: 520, flipScore: 7.5, energyPremium: 18, typicalDiscount: 22, dom: 60, fgStock: 55, flipNote: 'Top cluster: stock F/G abbondante + premio alto + QdV.', drivers: ['Diversificazione distretti', "Benetton-Diadora-De'Longhi", 'TAV Fase 1'], risks: [], note: '+18 pos. QdV 2025 (6° nazionale).', tags: ['Top', 'Long-term', 'Emerging'] },
  { id: 'oderzo', name: 'Oderzo', province: 'TV', x: 625, y: 345, price: 1950, rentLT: 9.5, yieldLT: 5.8, yieldST: null, score10y: 6.5, trend: 'stable', apprec: 2.0, invMin: 35, invMax: 65, flipScore: 4.5, energyPremium: 9, typicalDiscount: 18, dom: 85, fgStock: 55, flipNote: 'Marca, flip locale.', drivers: ['Centro Marca'], risks: [], note: 'Stabile, qualità Marca Trevigiana.', tags: ['Long-term'] },
  { id: 'motta', name: 'Motta di Livenza', province: 'TV', x: 660, y: 335, price: 1232, rentLT: 7.5, yieldLT: 7.3, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 20, invMax: 38, flipScore: 3.0, energyPremium: 5, typicalDiscount: 20, dom: 120, fgStock: 60, flipNote: 'Mercato piccolo ORAS-dipendente, NO flip.', drivers: ['ORAS 430+ professionisti', 'Riabilitazione regionale'], risks: ['Mono-driver ORAS'], note: '174 PL ORAS, espansione +13 PL 2026.', tags: ['Long-term', 'Mispriced', 'Nicchia'] },
  { id: 'mogliano', name: 'Mogliano Veneto', province: 'TV', x: 575, y: 405, price: 2318, rentLT: 10.5, yieldLT: 5.4, yieldST: null, score10y: 7.0, trend: 'up', apprec: 3.5, invMin: 50, invMax: 95, flipScore: 5.5, energyPremium: 12, typicalDiscount: 18, dom: 65, fgStock: 50, flipNote: 'Cintura TV, flip qualità medio.', drivers: ['Pendolarismo VE-TV', 'TAV beneficiario'], risks: [], note: 'Cintura Treviso, qualità della vita alta.', tags: ['Long-term'] },
  { id: 'casalesile', name: 'Casale sul Sile', province: 'TV', x: 580, y: 390, price: 1200, rentLT: 8.3, yieldLT: 7.0, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 18, invMax: 35, flipScore: 3.5, energyPremium: 7, typicalDiscount: 18, dom: 110, fgStock: 55, flipNote: 'Periferia TV, mercato thin.', drivers: ['Periferia TV'], risks: [], note: 'Mercato locale.', tags: ['Long-term'] },
  { id: 'roncade', name: 'Roncade', province: 'TV', x: 600, y: 395, price: 1125, rentLT: 8.5, yieldLT: 7.5, yieldST: null, score10y: 6.5, trend: 'up', apprec: 3.0, invMin: 22, invMax: 42, flipScore: 4.0, energyPremium: 8, typicalDiscount: 20, dom: 95, fgStock: 58, flipNote: 'H-Farm vicinanza, flip selettivo.', drivers: ['H-Farm (utile €34M 2025)', 'Industria', 'Innovation workers'], risks: [], note: 'Watchlist positiva selettiva.', tags: ['Mispriced', 'Long-term', 'Emerging'] },
  { id: 'conegliano', name: 'Conegliano', province: 'TV', x: 555, y: 295, price: 2056, rentLT: 9.9, yieldLT: 5.4, yieldST: 15.0, score10y: 8.0, trend: 'up', apprec: 5.0, invMin: 110, invMax: 190, flipScore: 6.5, energyPremium: 15, typicalDiscount: 18, dom: 70, fgStock: 55, flipNote: 'UNESCO + TAV, flip premium su classe B.', drivers: ['UNESCO Prosecco +9,2% arrivi 2024', '+7,3% 2025', 'TAV Conegliano'], risks: [], note: 'Asset livello istituzionale, turismo strutturalmente in crescita.', tags: ['Top', 'Short-term', 'Emerging'] },
  { id: 'vittorio', name: 'Vittorio Veneto', province: 'TV', x: 540, y: 270, price: 1206, rentLT: 9.9, yieldLT: 9.8, yieldST: 15.0, score10y: 6.5, trend: 'up', apprec: 3.5, invMin: 80, invMax: 140, flipScore: 3.5, energyPremium: 6, typicalDiscount: 22, dom: 130, fgStock: 65, flipNote: 'P&L palazzina -9,2% scenario base. Solo buy-to-rent.', drivers: ['Permasteelisa HQ 3.900 dip.', 'Vicinanza UNESCO'], risks: ['Atlas Holdings USA owner'], note: 'Gioiello nascosto. Real estate fuori radar vs Conegliano.', tags: ['Mispriced', 'Long-term', 'Emerging'] },
  { id: 'castelfranco', name: 'Castelfranco Veneto', province: 'TV', x: 490, y: 380, price: 1850, rentLT: 8.5, yieldLT: 5.5, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 2.0, invMin: 60, invMax: 105, flipScore: 4.5, energyPremium: 10, typicalDiscount: 18, dom: 80, fgStock: 55, flipNote: 'Borgo storico, flip vincolato.', drivers: ['Centro storico medievale'], risks: [], note: 'Stabile minore.', tags: ['Long-term'] },
  { id: 'montebelluna', name: 'Montebelluna', province: 'TV', x: 500, y: 345, price: 1650, rentLT: 8.5, yieldLT: 6.2, yieldST: null, score10y: 7.0, trend: 'up', apprec: 3.5, invMin: 70, invMax: 120, flipScore: 5.0, energyPremium: 11, typicalDiscount: 18, dom: 75, fgStock: 55, flipNote: 'Sportsystem ripresa, flip medio.', drivers: ['Sportsystem +3,2% Q1 2025', '400 aziende 9000 addetti', 'Diadora-Lotto-Scarpa'], risks: [], note: 'Distretto in ripresa, +41 occupazione Q1 2025.', tags: ['Long-term', 'Emerging'] },
  { id: 'asolo', name: 'Asolo', province: 'TV', x: 480, y: 325, price: 2400, rentLT: 10.0, yieldLT: 5.0, yieldST: 14.0, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 18, invMax: 35, flipScore: 4.0, energyPremium: 12, typicalDiscount: 15, dom: 90, fgStock: 65, flipNote: 'Borgo storico, vincoli paesaggistici.', drivers: ['Borgo storico premium'], risks: ['Mercato nicchia eventi'], note: 'Cultural cluster minore.', tags: ['Short-term', 'Nicchia'] },
  { id: 'valdobbiadene', name: 'Valdobbiadene', province: 'TV', x: 510, y: 290, price: 1550, rentLT: 7.5, yieldLT: 6.5, yieldST: 16.0, score10y: 7.5, trend: 'up', apprec: 4.0, invMin: 30, invMax: 55, flipScore: 5.0, energyPremium: 13, typicalDiscount: 18, dom: 80, fgStock: 58, flipNote: 'Enoturismo, flip su ville-resort.', drivers: ['Prosecco DOCG', 'UNESCO'], risks: [], note: 'Enoturismo strutturalmente solido.', tags: ['Short-term', 'Emerging'] },
  { id: 'padova', name: 'Padova centro', province: 'PD', x: 460, y: 445, price: 3239, rentLT: 15.6, yieldLT: 5.8, yieldST: 20.0, score10y: 6.0, trend: 'stable', apprec: 3.0, invMin: 280, invMax: 480, flipScore: 6.5, energyPremium: 14, typicalDiscount: 12, dom: 45, fgStock: 60, flipNote: 'Premium ma ticket entrata alto.', drivers: ['Centro storico UNESCO Scrovegni'], risks: ['Possibile contagio reg. STR'], note: 'Yield compresso da prezzi alti.', tags: ['Short-term', 'Premium'] },
  { id: 'arcella', name: 'Padova Arcella', province: 'PD', x: 455, y: 435, price: 900, rentLT: 7.7, yieldLT: 11.5, yieldST: 19.5, score10y: 8.0, trend: 'up', apprec: 5.5, invMin: 90, invMax: 160, flipScore: 9.5, energyPremium: 12, typicalDiscount: 28, dom: 45, fgStock: 70, flipNote: 'Scenario A P&L: +15,8% in 6 mesi. Best flip Veneto.', drivers: ['UniPD 76mila iscritti', 'Tram SIR1 attivo', 'Gentrificazione'], risks: ['Saturazione PBSA post 2027'], note: 'Best yield Veneto. SIR1 -30/60% traffico.', tags: ['Top', 'Mispriced', 'Universitario'] },
  { id: 'forcellini', name: 'Padova Forcellini', province: 'PD', x: 470, y: 455, price: 1600, rentLT: 8.5, yieldLT: 9.0, yieldST: 18.0, score10y: 8.5, trend: 'up', apprec: 4.5, invMin: 60, invMax: 110, flipScore: 9.0, energyPremium: 12, typicalDiscount: 22, dom: 50, fgStock: 60, flipNote: 'Top flip cluster: doppio driver università + ospedale.', drivers: ['UniPD', 'Ospedale Padova', 'SIR3 in arrivo'], risks: ['PBSA pipeline 1.500 PL'], note: 'Doppio driver università + ospedale.', tags: ['Top', 'Universitario'] },
  { id: 'mortise', name: 'Padova Mortise/Stanga', province: 'PD', x: 465, y: 440, price: 1650, rentLT: 8.5, yieldLT: 6.5, yieldST: null, score10y: 8.5, trend: 'up', apprec: 4.5, invMin: 75, invMax: 130, flipScore: 8.5, energyPremium: 12, typicalDiscount: 22, dom: 50, fgStock: 60, flipNote: 'Triplo driver, flip solido.', drivers: ['Ospedale Padova grande', 'UniPD', 'Stazione'], risks: [], note: 'Triplo driver: sanitari + studenti + pendolari.', tags: ['Top', 'Long-term', 'Universitario'] },
  { id: 'voltabarozzo', name: 'Padova Voltabarozzo', province: 'PD', x: 462, y: 460, price: 1150, rentLT: 7.5, yieldLT: 9.0, yieldST: null, score10y: 8.0, trend: 'up', apprec: 5.0, invMin: 35, invMax: 65, flipScore: 8.5, energyPremium: 12, typicalDiscount: 25, dom: 50, fgStock: 65, flipNote: 'Tram in arrivo, flip+upside da SIR3.', drivers: ['SIR2/SIR3 tram in arrivo 2026', 'Flusso studentesco'], risks: [], note: 'Beneficiario diretto tram metropolitano.', tags: ['Top', 'Mispriced', 'Long-term'] },
  { id: 'abano', name: 'Abano Terme', province: 'PD', x: 445, y: 460, price: 2330, rentLT: 10.1, yieldLT: 5.2, yieldST: 13.0, score10y: 5.5, trend: 'stable', apprec: 1.0, invMin: 90, invMax: 150, flipScore: 4.0, energyPremium: 9, typicalDiscount: 15, dom: 100, fgStock: 60, flipNote: 'Termale, target clientela anziana.', drivers: ['Wellness 12 mesi'], risks: ['Invecchiamento clientela'], note: 'Possibile beneficiario lab WHO invecchiamento.', tags: ['Termale'] },
  { id: 'montegrotto', name: 'Montegrotto Terme', province: 'PD', x: 442, y: 467, price: 2380, rentLT: 9.7, yieldLT: 4.9, yieldST: 13.5, score10y: 5.5, trend: 'stable', apprec: 6.5, invMin: 70, invMax: 120, flipScore: 4.5, energyPremium: 10, typicalDiscount: 15, dom: 90, fgStock: 60, flipNote: 'Termale, flip medio.', drivers: ['Termale +13% prezzi YoY'], risks: ['Doppio invecchiamento DE+IT'], note: 'Cluster wellness storico.', tags: ['Termale'] },
  { id: 'cittadella', name: 'Cittadella', province: 'PD', x: 470, y: 380, price: 1450, rentLT: 7.5, yieldLT: 6.2, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 30, invMax: 55, flipScore: 4.0, energyPremium: 9, typicalDiscount: 18, dom: 85, fgStock: 55, flipNote: 'Borgo medievale.', drivers: ['Borgo medievale'], risks: [], note: 'Stabile, qualità.', tags: ['Long-term'] },
  { id: 'este', name: 'Este', province: 'PD', x: 415, y: 510, price: 1300, rentLT: 7.0, yieldLT: 6.5, yieldST: null, score10y: 5.0, trend: 'stable', apprec: 1.0, invMin: 28, invMax: 50, flipScore: 3.5, energyPremium: 7, typicalDiscount: 18, dom: 100, fgStock: 60, flipNote: 'Bassa padovana, flip marginale.', drivers: ['Mercato locale'], risks: [], note: 'Bassa padovana stabile.', tags: ['Long-term'] },
  { id: 'monselice', name: 'Monselice', province: 'PD', x: 430, y: 510, price: 1400, rentLT: 7.5, yieldLT: 6.4, yieldST: null, score10y: 5.0, trend: 'stable', apprec: 1.5, invMin: 30, invMax: 55, flipScore: 3.5, energyPremium: 7, typicalDiscount: 18, dom: 100, fgStock: 60, flipNote: 'Locale, flip marginale.', drivers: ['Mercato locale'], risks: [], note: 'Stabile, locale.', tags: ['Long-term'] },
  { id: 'albignasego', name: 'Albignasego', province: 'PD', x: 460, y: 470, price: 1750, rentLT: 8.5, yieldLT: 5.8, yieldST: null, score10y: 6.5, trend: 'up', apprec: 3.0, invMin: 55, invMax: 95, flipScore: 7.5, energyPremium: 12, typicalDiscount: 20, dom: 60, fgStock: 55, flipNote: 'Scenario C villa→duplex +10,8% se acquisto ≤200k.', drivers: ['Cintura padovana SIR3', 'Tram in arrivo'], risks: [], note: 'Beneficiario tram metropolitano.', tags: ['Long-term'] },
  { id: 'verona', name: 'Verona centro storico', province: 'VR', x: 240, y: 440, price: 4500, rentLT: 18.0, yieldLT: 4.8, yieldST: 16.5, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 220, invMax: 380, flipScore: 7.0, energyPremium: 25, typicalDiscount: 12, dom: 55, fgStock: 60, flipNote: 'Premio energetico altissimo ma ticket entrata alto.', drivers: ['Arena chiusura Olimpiadi 2026', 'Turismo culturale'], risks: ['Possibile reg. STR'], note: 'Yield compresso ma asset patrimoniale.', tags: ['Short-term', 'Premium'] },
  { id: 'veronetta', name: 'Verona Veronetta', province: 'VR', x: 255, y: 445, price: 3000, rentLT: 12.0, yieldLT: 5.5, yieldST: 17.5, score10y: 7.5, trend: 'stable', apprec: 3.0, invMin: 110, invMax: 190, flipScore: 8.0, energyPremium: 28, typicalDiscount: 18, dom: 55, fgStock: 65, flipNote: 'Top flip Verona: premio +31% massimo.', drivers: ['UniVR 25mila studenti', 'Cultura'], risks: ['Rischio normativo STR'], note: 'Storico universitario.', tags: ['Universitario'] },
  { id: 'cesiolo', name: 'Verona Cesiolo', province: 'VR', x: 245, y: 425, price: 2000, rentLT: 10.0, yieldLT: 10.0, yieldST: null, score10y: 9.0, trend: 'up', apprec: 4.0, invMin: 55, invMax: 95, flipScore: 9.0, energyPremium: 28, typicalDiscount: 22, dom: 50, fgStock: 58, flipNote: 'Top flip Verona: AOUI + premio +31% + entrata bassa.', drivers: ['AOUI 5.148 dipendenti', 'Olimpiadi ospedale ufficiale', '€32M investimenti 2025'], risks: [], note: 'Cluster più resiliente del Veneto. Sanitari + Olimpiadi.', tags: ['Top', 'Mispriced', 'Long-term'] },
  { id: 'borgotrento', name: 'Verona Borgo Trento', province: 'VR', x: 235, y: 425, price: 2050, rentLT: 9.0, yieldLT: 7.5, yieldST: null, score10y: 9.0, trend: 'up', apprec: 4.0, invMin: 75, invMax: 130, flipScore: 9.0, energyPremium: 28, typicalDiscount: 20, dom: 50, fgStock: 58, flipNote: 'Top flip palazzina: scenario alternativo P&L +180-220k.', drivers: ['Ospedale Maggiore', 'AOUI', 'Trauma Center 55K accessi'], risks: [], note: 'Top sanitario + Olimpiadi 2026.', tags: ['Top', 'Long-term'] },
  { id: 'borgovenezia', name: 'Verona Borgo Venezia', province: 'VR', x: 265, y: 435, price: 1850, rentLT: 9.5, yieldLT: 7.3, yieldST: 14.0, score10y: 7.5, trend: 'up', apprec: 3.5, invMin: 90, invMax: 150, flipScore: 7.5, energyPremium: 25, typicalDiscount: 20, dom: 60, fgStock: 60, flipNote: 'Premio energetico Verona, flip solido.', drivers: ['Studenti Musicisti', 'Cresce +2,4% YoY'], risks: [], note: 'Asset entry-level con upside.', tags: ['Universitario', 'Emerging'] },
  { id: 'borgoroma', name: 'Verona Borgo Roma', province: 'VR', x: 240, y: 460, price: 1650, rentLT: 9.0, yieldLT: 7.5, yieldST: 14.0, score10y: 7.0, trend: 'up', apprec: 3.0, invMin: 100, invMax: 170, flipScore: 7.0, energyPremium: 22, typicalDiscount: 22, dom: 65, fgStock: 60, flipNote: 'Antisismica 2028 in corso, attenzione cantieri.', drivers: ['Policlinico Sud', 'Università'], risks: ['Lavori antisismici 2028'], note: 'Cantierizzazione in corso ma fondamentali solidi.', tags: ['Long-term'] },
  { id: 'borgomilano', name: 'Verona Borgo Milano', province: 'VR', x: 225, y: 440, price: 1550, rentLT: 7.5, yieldLT: 5.8, yieldST: 15.5, score10y: 6.5, trend: 'stable', apprec: 2.5, invMin: 80, invMax: 140, flipScore: 6.5, energyPremium: 22, typicalDiscount: 20, dom: 65, fgStock: 60, flipNote: 'Tangenziale, flip residenziale medio.', drivers: ['Tangenziale', 'B&B'], risks: [], note: 'Mix uso, accessibile.', tags: ['Long-term'] },
  { id: 'bardolino', name: 'Bardolino', province: 'VR', x: 165, y: 400, price: 3000, rentLT: 18.0, yieldLT: 5.0, yieldST: 24.5, score10y: 7.0, trend: 'stable', apprec: 5.5, invMin: 130, invMax: 220, flipScore: 6.0, energyPremium: 15, typicalDiscount: 10, dom: 75, fgStock: 60, flipNote: 'Premium Garda, flip su appartamenti vista.', drivers: ['38,4% turismo tedesco Garda', 'Cliente alto-spendente'], risks: ['Climate Garda 2022-24'], note: 'Top yield STR Veneto. Stagione lunga.', tags: ['Short-term', 'Lago'] },
  { id: 'peschiera', name: 'Peschiera del Garda', province: 'VR', x: 155, y: 430, price: 2750, rentLT: 16.0, yieldLT: 5.0, yieldST: 19.0, score10y: 7.0, trend: 'stable', apprec: 4.0, invMin: 140, invMax: 240, flipScore: 5.5, energyPremium: 13, typicalDiscount: 10, dom: 80, fgStock: 60, flipNote: 'Garda, flip STR-ready.', drivers: ['Garda + Gardaland'], risks: ['Climate change'], note: 'Eventi extra-stagionali.', tags: ['Short-term', 'Lago'] },
  { id: 'lazise', name: 'Lazise', province: 'VR', x: 160, y: 415, price: 3150, rentLT: 17.0, yieldLT: 5.0, yieldST: 19.0, score10y: 7.0, trend: 'stable', apprec: 4.5, invMin: 110, invMax: 190, flipScore: 5.5, energyPremium: 13, typicalDiscount: 10, dom: 80, fgStock: 60, flipNote: 'Garda, flip STR-ready.', drivers: ['Garda turismo internazionale'], risks: [], note: 'STR Garda solido.', tags: ['Short-term', 'Lago'] },
  { id: 'garda', name: 'Garda', province: 'VR', x: 170, y: 390, price: 3500, rentLT: 15.0, yieldLT: 4.5, yieldST: 11.0, score10y: 6.0, trend: 'down', apprec: 1.5, invMin: 90, invMax: 160, flipScore: 3.5, energyPremium: 10, typicalDiscount: 8, dom: 110, fgStock: 60, flipNote: 'Saturazione, NO flip.', drivers: ['Brand Garda'], risks: ['Supply +42,8% YoY', 'Saturazione locale'], note: 'Saturazione conclamata su comune.', tags: ['Saturazione'] },
  { id: 'malcesine', name: 'Malcesine', province: 'VR', x: 165, y: 340, price: 3500, rentLT: 14.0, yieldLT: 4.5, yieldST: 13.0, score10y: 6.5, trend: 'stable', apprec: 3.5, invMin: 100, invMax: 180, flipScore: 4.5, energyPremium: 12, typicalDiscount: 10, dom: 95, fgStock: 60, flipNote: 'CAPEX alto, flip difficile.', drivers: ['Garda nord'], risks: ['CAPEX alto'], note: 'STR moderato, prezzi premium.', tags: ['Short-term'] },
  { id: 'villafranca', name: 'Villafranca di Verona', province: 'VR', x: 215, y: 470, price: 1500, rentLT: 8.0, yieldLT: 6.4, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.0, invMin: 45, invMax: 80, flipScore: 4.5, energyPremium: 15, typicalDiscount: 18, dom: 80, fgStock: 55, flipNote: 'Periferia VR, flip locale.', drivers: ['Manifattura/logistica'], risks: [], note: 'Mercato locale.', tags: ['Long-term'] },
  { id: 'sanbonifacio', name: 'San Bonifacio', province: 'VR', x: 290, y: 460, price: 1450, rentLT: 7.8, yieldLT: 6.5, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 1.5, invMin: 35, invMax: 65, flipScore: 4.0, energyPremium: 13, typicalDiscount: 18, dom: 90, fgStock: 60, flipNote: 'Locale, flip modesto.', drivers: ['Mercato locale'], risks: [], note: 'Stabile periferico.', tags: ['Long-term'] },
  { id: 'bussolengo', name: 'Bussolengo', province: 'VR', x: 215, y: 425, price: 1600, rentLT: 8.5, yieldLT: 6.4, yieldST: null, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 40, invMax: 75, flipScore: 5.0, energyPremium: 17, typicalDiscount: 18, dom: 75, fgStock: 55, flipNote: 'Cintura Verona, flip modesto.', drivers: ['Logistica Verona'], risks: [], note: 'Quadrante Europa vicinanza.', tags: ['Long-term'] },
  { id: 'legnago', name: 'Legnago', province: 'VR', x: 275, y: 520, price: 1350, rentLT: 7.5, yieldLT: 6.7, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 1.0, invMin: 40, invMax: 70, flipScore: 3.5, energyPremium: 12, typicalDiscount: 20, dom: 95, fgStock: 60, flipNote: 'Bassa veronese, flip marginale.', drivers: ['Bassa veronese'], risks: [], note: 'Mercato locale.', tags: ['Long-term'] },
  { id: 'negrar', name: 'Negrar (Valpolicella)', province: 'VR', x: 220, y: 410, price: 2400, rentLT: 9.5, yieldLT: 4.8, yieldST: 13.0, score10y: 6.5, trend: 'up', apprec: 3.0, invMin: 30, invMax: 55, flipScore: 5.0, energyPremium: 18, typicalDiscount: 15, dom: 80, fgStock: 55, flipNote: 'Wine tourism, flip nicchia.', drivers: ['Enoturismo Valpolicella'], risks: [], note: 'Wine tourism nicchia.', tags: ['Short-term'] },
  { id: 'vicenza', name: 'Vicenza centro', province: 'VI', x: 360, y: 410, price: 2281, rentLT: 11.3, yieldLT: 5.9, yieldST: 20.5, score10y: 7.0, trend: 'down', apprec: 2.0, invMin: 180, invMax: 310, flipScore: 6.0, energyPremium: 15, typicalDiscount: 18, dom: 80, fgStock: 60, flipNote: 'QdV in calo, flip cauto su Palladio.', drivers: ['Palladio UNESCO', 'VicenzaOro'], risks: ['QdV -10 pos. 2025', 'Distretto orafo dazi USA'], note: 'STR sottosviluppato ma deterioramento QdV.', tags: ['Short-term', 'Mispriced'] },
  { id: 'bassano', name: 'Bassano del Grappa', province: 'VI', x: 410, y: 330, price: 1916, rentLT: 11.3, yieldLT: 7.0, yieldST: 22.0, score10y: 6.0, trend: 'stable', apprec: 2.5, invMin: 130, invMax: 220, flipScore: 5.5, energyPremium: 13, typicalDiscount: 15, dom: 80, fgStock: 60, flipNote: 'Cultura, flip su centro storico.', drivers: ['Turismo enogastronomico', 'Cultura'], risks: ['Mercato piccolo'], note: 'Best ratio prezzo/turismo. 42mila ab.', tags: ['Short-term', 'Mispriced'] },
  { id: 'schio', name: 'Schio', province: 'VI', x: 340, y: 340, price: 1233, rentLT: 8.3, yieldLT: 8.0, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 2.0, invMin: 70, invMax: 120, flipScore: 4.0, energyPremium: 9, typicalDiscount: 22, dom: 100, fgStock: 60, flipNote: 'Industriale stabile, flip locale.', drivers: ['Distretto precision', 'Beltrame-Xylem'], risks: [], note: 'Stabile industriale.', tags: ['Long-term'] },
  { id: 'thiene', name: 'Thiene', province: 'VI', x: 355, y: 350, price: 1580, rentLT: 8.9, yieldLT: 6.7, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 2.0, invMin: 45, invMax: 80, flipScore: 4.0, energyPremium: 10, typicalDiscount: 18, dom: 90, fgStock: 55, flipNote: 'Manifattura, flip marginale.', drivers: ['Manifattura'], risks: [], note: 'Locale stabile.', tags: ['Long-term'] },
  { id: 'arzignano', name: 'Arzignano', province: 'VI', x: 325, y: 425, price: 1781, rentLT: 9.0, yieldLT: 6.0, yieldST: null, score10y: 3.0, trend: 'down', apprec: -1.0, invMin: 50, invMax: 90, flipScore: 1.5, energyPremium: 6, typicalDiscount: 25, dom: 180, fgStock: 65, flipNote: 'Convergenza rischi, NO flip.', drivers: ['Distretto conciario'], risks: ['Dazi USA', 'Caos politico 2025', 'Aggregazioni distretto'], note: 'ZONA DA EVITARE. Convergenza rischi.', tags: ['Da disinvestire', 'Rischio'] },
  { id: 'valdagno', name: 'Valdagno', province: 'VI', x: 305, y: 395, price: 1150, rentLT: 7.0, yieldLT: 7.3, yieldST: null, score10y: 3.0, trend: 'down', apprec: -1.5, invMin: 50, invMax: 95, flipScore: 1.5, energyPremium: 5, typicalDiscount: 28, dom: 200, fgStock: 70, flipNote: 'Marzotto declino, NO flip.', drivers: ['Storico Marzotto'], risks: ['Marzotto-Favrin 80% aprile 2025', 'Declino strutturale tessile'], note: 'Città mono-aziendale in declino.', tags: ['Da disinvestire', 'Rischio'] },
  { id: 'asiago', name: 'Asiago', province: 'VI', x: 390, y: 270, price: 2752, rentLT: 16.0, yieldLT: 6.0, yieldST: 11.0, score10y: 6.0, trend: 'stable', apprec: 3.5, invMin: 130, invMax: 220, flipScore: 4.5, energyPremium: 11, typicalDiscount: 12, dom: 100, fgStock: 65, flipNote: 'Montagna, stagionale.', drivers: ['Sci/estate'], risks: ['Climate Alpi'], note: 'Max provincia, stagionale.', tags: ['Short-term', 'Montagna'] },
  { id: 'marostica', name: 'Marostica', province: 'VI', x: 395, y: 345, price: 1550, rentLT: 8.0, yieldLT: 6.0, yieldST: null, score10y: 5.5, trend: 'stable', apprec: 2.0, invMin: 30, invMax: 55, flipScore: 4.0, energyPremium: 11, typicalDiscount: 18, dom: 90, fgStock: 55, flipNote: 'Borgo storico, vincoli.', drivers: ['Borgo storico'], risks: [], note: 'Locale stabile.', tags: ['Long-term'] },
  { id: 'montecchio', name: 'Montecchio Maggiore', province: 'VI', x: 320, y: 425, price: 1550, rentLT: 8.0, yieldLT: 6.2, yieldST: null, score10y: 5.0, trend: 'stable', apprec: 1.5, invMin: 30, invMax: 55, flipScore: 3.5, energyPremium: 10, typicalDiscount: 20, dom: 100, fgStock: 60, flipNote: 'Periferia industriale, flip rischioso.', drivers: ['Periferia industriale'], risks: ['Esposizione orafa/conciaria'], note: 'Locale.', tags: ['Long-term'] },
  { id: 'belluno', name: 'Belluno città', province: 'BL', x: 510, y: 220, price: 1522, rentLT: 8.7, yieldLT: 6.9, yieldST: null, score10y: 4.5, trend: 'stable', apprec: 8.5, invMin: 60, invMax: 110, flipScore: 4.5, energyPremium: 12, typicalDiscount: 22, dom: 110, fgStock: 65, flipNote: 'Demografia debole ma +17% YoY.', drivers: ['Capoluogo Luxottica indotto'], risks: ['Provincia -3,8% al 2031', '>30% over-65 entro 2031'], note: '+17% YoY ma trend provinciale negativo.', tags: ['Long-term'] },
  { id: 'cortina', name: "Cortina d'Ampezzo", province: 'BL', x: 590, y: 130, price: 12900, rentLT: 28.0, yieldLT: 3.0, yieldST: 7.0, score10y: 4.0, trend: 'down', apprec: 2.0, invMin: 180, invMax: 320, flipScore: 3.5, energyPremium: 14, typicalDiscount: 8, dom: 150, fgStock: 60, flipNote: 'Asset patrimoniale, NO cash flow flip.', drivers: ['Olimpiadi 2026'], risks: ['Pista bob €120M legacy', 'Solo 40/98 opere', 'Climate Alpi'], note: 'Asset patrimoniale, no cash-flow.', tags: ['Premium', 'Da evitare cash-flow'] },
  { id: 'sanvito', name: 'San Vito di Cadore', province: 'BL', x: 580, y: 145, price: 3800, rentLT: 30.3, yieldLT: 9.0, yieldST: 14.0, score10y: 4.5, trend: 'down', apprec: 1.0, invMin: 35, invMax: 65, flipScore: 3.0, energyPremium: 10, typicalDiscount: 15, dom: 140, fgStock: 60, flipNote: 'Cadore in declino, NO flip.', drivers: ['Cadore tradizione'], risks: ['Spopolamento Cadore -7,5%'], note: 'Affitti max provincia ma trend area negativo.', tags: ['Short-term', 'Montagna'] },
  { id: 'falcade', name: 'Falcade', province: 'BL', x: 540, y: 155, price: 3000, rentLT: 14.0, yieldLT: 5.5, yieldST: 17.0, score10y: 4.5, trend: 'down', apprec: 0.5, invMin: 25, invMax: 50, flipScore: 3.0, energyPremium: 9, typicalDiscount: 15, dom: 140, fgStock: 60, flipNote: 'Climate alpine, NO flip.', drivers: ['Dolomiti accessibili'], risks: ['Climate change neve'], note: 'Stagionale ad alto rischio climatico.', tags: ['Short-term', 'Montagna'] },
  { id: 'arabba', name: 'Arabba', province: 'BL', x: 545, y: 130, price: 5000, rentLT: 22.0, yieldLT: 5.0, yieldST: 13.0, score10y: 4.5, trend: 'stable', apprec: 2.0, invMin: 18, invMax: 35, flipScore: 3.0, energyPremium: 10, typicalDiscount: 10, dom: 150, fgStock: 60, flipNote: 'CAPEX altissimo, flip difficile.', drivers: ['Sellaronda premium'], risks: ['CAPEX altissimo', 'Climate'], note: 'Premium sci.', tags: ['Short-term', 'Premium', 'Montagna'] },
  { id: 'auronzo', name: 'Auronzo di Cadore', province: 'BL', x: 600, y: 155, price: 2200, rentLT: 11.0, yieldLT: 6.0, yieldST: 13.0, score10y: 4.0, trend: 'down', apprec: 0.0, invMin: 30, invMax: 55, flipScore: 2.5, energyPremium: 8, typicalDiscount: 18, dom: 160, fgStock: 60, flipNote: 'Cadore in declino, NO flip.', drivers: ['Cadore'], risks: ['Spopolamento -7,5% Cadore'], note: 'Stagionalità marcata.', tags: ['Short-term', 'Rischio'] },
  { id: 'sappada', name: 'Sappada', province: 'BL', x: 660, y: 145, price: 2400, rentLT: 11.0, yieldLT: 5.5, yieldST: 12.0, score10y: 4.0, trend: 'down', apprec: 0.5, invMin: 22, invMax: 42, flipScore: 2.5, energyPremium: 8, typicalDiscount: 18, dom: 160, fgStock: 60, flipNote: 'Demografia debole, NO flip.', drivers: ['Montagna minore'], risks: ['Demografia'], note: 'Provincia in declino.', tags: ['Short-term', 'Rischio'] },
  { id: 'alleghe', name: 'Alleghe', province: 'BL', x: 545, y: 175, price: 2500, rentLT: 11.0, yieldLT: 5.3, yieldST: 12.0, score10y: 4.5, trend: 'down', apprec: 1.0, invMin: 20, invMax: 38, flipScore: 2.5, energyPremium: 8, typicalDiscount: 15, dom: 150, fgStock: 60, flipNote: 'Demografia provincia debole.', drivers: ['Lago + sci'], risks: ['Demografia provincia'], note: 'Cluster minore.', tags: ['Short-term'] },
  { id: 'feltre', name: 'Feltre', province: 'BL', x: 470, y: 250, price: 1024, rentLT: 6.1, yieldLT: 7.1, yieldST: 11.0, score10y: 5.0, trend: 'stable', apprec: 1.0, invMin: 35, invMax: 65, flipScore: 3.5, energyPremium: 10, typicalDiscount: 22, dom: 120, fgStock: 65, flipNote: 'Solo per locali.', drivers: ['Cash-on-cash interessante'], risks: ['Provincia in calo'], note: 'Solo per investitori locali.', tags: ['Long-term', 'Mispriced'] },
  { id: 'longarone', name: 'Longarone', province: 'BL', x: 530, y: 220, price: 1250, rentLT: 7.5, yieldLT: 7.2, yieldST: null, score10y: 4.5, trend: 'stable', apprec: 1.0, invMin: 18, invMax: 32, flipScore: 3.0, energyPremium: 8, typicalDiscount: 22, dom: 130, fgStock: 65, flipNote: 'Luxottica-dipendente.', drivers: ['Luxottica indotto'], risks: ['Provincia in calo'], note: 'Mono-dipendenza Luxottica.', tags: ['Long-term'] },
  { id: 'pievecadore', name: 'Pieve di Cadore', province: 'BL', x: 590, y: 170, price: 2200, rentLT: 10.0, yieldLT: 5.5, yieldST: 12.0, score10y: 4.0, trend: 'down', apprec: 0.0, invMin: 22, invMax: 40, flipScore: 2.5, energyPremium: 8, typicalDiscount: 18, dom: 160, fgStock: 60, flipNote: 'Cadore in declino.', drivers: ['Cadore'], risks: ['Spopolamento area'], note: 'Stagionale.', tags: ['Short-term', 'Rischio'] },
  { id: 'rovigo', name: 'Rovigo città', province: 'RO', x: 415, y: 555, price: 1200, rentLT: 8.7, yieldLT: 8.7, yieldST: null, score10y: 2.5, trend: 'down', apprec: -0.5, invMin: 100, invMax: 175, flipScore: 1.5, energyPremium: 6, typicalDiscount: 28, dom: 200, fgStock: 70, flipNote: 'Peggior demografia. NO flip.', drivers: ['Capoluogo'], risks: ['-12,4% PIL lavorativa 2035', 'Peggior demografia Centro-Nord'], note: 'Yield alto ma declino strutturale.', tags: ['Da evitare strategicamente', 'Rischio demografico'] },
  { id: 'adria', name: 'Adria', province: 'RO', x: 495, y: 555, price: 1050, rentLT: 7.0, yieldLT: 8.0, yieldST: null, score10y: 3.0, trend: 'down', apprec: -1.0, invMin: 40, invMax: 75, flipScore: 1.5, energyPremium: 5, typicalDiscount: 30, dom: 220, fgStock: 70, flipNote: 'Spopolamento, NO flip.', drivers: [], risks: ['Spopolamento'], note: 'Mercato piccolo in declino.', tags: ['Rischio demografico'] },
  { id: 'portotolle', name: 'Porto Tolle', province: 'RO', x: 580, y: 590, price: 850, rentLT: 5.5, yieldLT: 7.8, yieldST: null, score10y: 3.0, trend: 'down', apprec: -1.0, invMin: 20, invMax: 40, flipScore: 1.0, energyPremium: 4, typicalDiscount: 30, dom: 240, fgStock: 70, flipNote: 'Delta Po in declino.', drivers: ['Delta Po'], risks: ['Demografia'], note: 'Costa Polesine.', tags: ['Rischio demografico'] },
  { id: 'rosolina', name: 'Rosolina (Delta Po)', province: 'RO', x: 555, y: 550, price: 2950, rentLT: 17.9, yieldLT: 7.3, yieldST: 14.0, score10y: 4.5, trend: 'stable', apprec: 1.5, invMin: 90, invMax: 160, flipScore: 3.5, energyPremium: 8, typicalDiscount: 15, dom: 130, fgStock: 60, flipNote: 'Stagionale Polesine.', drivers: ['STR estivo Delta'], risks: ['Stagionalità', 'Provincia in declino'], note: 'Eccezione nicchia in Polesine.', tags: ['Short-term', 'Stagionale'] },
  { id: 'lendinara', name: 'Lendinara', province: 'RO', x: 365, y: 555, price: 750, rentLT: 5.5, yieldLT: 8.8, yieldST: null, score10y: 2.5, trend: 'down', apprec: -1.5, invMin: 25, invMax: 45, flipScore: 1.0, energyPremium: 4, typicalDiscount: 30, dom: 240, fgStock: 70, flipNote: 'Spopolamento estremo.', drivers: [], risks: ['Spopolamento'], note: 'Da evitare.', tags: ['Rischio demografico'] },
  { id: 'badia', name: 'Badia Polesine', province: 'RO', x: 320, y: 545, price: 750, rentLT: 5.5, yieldLT: 8.8, yieldST: null, score10y: 2.5, trend: 'down', apprec: -1.5, invMin: 22, invMax: 42, flipScore: 1.0, energyPremium: 4, typicalDiscount: 30, dom: 240, fgStock: 70, flipNote: 'Spopolamento estremo.', drivers: [], risks: ['Spopolamento'], note: 'Da evitare.', tags: ['Rischio demografico'] },
];

const insert = db.prepare(`
  INSERT OR REPLACE INTO zones
  (id, name, province, x, y, price, rent_lt, yield_lt, yield_st, score_10y, trend, apprec,
   inv_min, inv_max, flip_score, energy_premium, typical_discount, dom, fg_stock,
   flip_note, note, tags, drivers, risks)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((zones: typeof ZONES) => {
  for (const z of zones) {
    insert.run(
      z.id, z.name, z.province, z.x, z.y, z.price, z.rentLT, z.yieldLT, z.yieldST,
      z.score10y, z.trend, z.apprec, z.invMin, z.invMax, z.flipScore, z.energyPremium,
      z.typicalDiscount, z.dom, z.fgStock, z.flipNote, z.note,
      JSON.stringify(z.tags), JSON.stringify(z.drivers), JSON.stringify(z.risks)
    );
  }
});

insertMany(ZONES);

console.log(`Seeded ${ZONES.length} zones into ${DB_PATH}`);
db.close();
